### ISSUE TITLE
可否求个交流群

### ISSUE THREAD

**Issue by ElainaFanBoy** [abrahum/nonebot_plugin_cocdicer#11]
指令这块还是没弄懂，想学习一下
readme里的那两个.rdbba#2 70和.ra2d8+10 70我试了下没成功触发

**Comment by abrahum** [comment]
可以去加入 [nonebot2](https://github.com/nonebot/nonebot2/) 的交流群，应该是你的 nonebot2 没有配置妥当

**Comment by ElainaFanBoy** [comment]
> 可以去加入 [nonebot2](https://github.com/nonebot/nonebot2/) 的交流群，应该是你的 nonebot2 没有配置妥当

> 可以去加入 [nonebot2](https://github.com/nonebot/nonebot2/) 的交流群，应该是你的 nonebot2 没有配置妥当

不是吧，我依赖和插件都成功安装并加载了，但是指令好像就是不对

**Comment by ElainaFanBoy** [comment]
> 可以去加入 [nonebot2](https://github.com/nonebot/nonebot2/) 的交流群，应该是你的 nonebot2 没有配置妥当

![IMG_20230409_093433.jpg](https://user-images.githubusercontent.com/56375835/230749767-437d916d-43a6-4279-8894-14059bf5cb56.jpg)

**Comment by abrahum** [comment]
啊，想起来了，现在检定不用加a了，后边加空格和数字就会自动检定，换了diro readme和帮助信息没改

**Comment by abrahum** [comment]
<img width="155" alt="image" src="https://user-images.githubusercontent.com/18395948/230750741-9f3b2328-f680-490f-b21d-78d5a73855aa.png">

**Comment by ElainaFanBoy** [comment]
> 啊，想起来了，现在检定不用加a了，后边加空格和数字就会自动检定，换了diro readme和帮助信息没改

原来如此，辛苦了
