### ISSUE TITLE
无法进行类似rd6这样子的判定

### ISSUE THREAD

**Issue by LycanW** [abrahum/nonebot_plugin_cocdicer#2]
。r指令有问题，无法决定数值
。ra无法判定成功或失败

**Comment by abrahum** [comment]
请附上你的测试用例，这里测试`.rd6`与`.ra 60`均可以正常返回。

目前所有指令仅响应`.`开头命令，无法响应`。`开头指令（下个版本会增加`。`指令开关）

`.ra`指令请注意判定必须使用1D100骰子，判定数值必须使用空格隔开，否则会忽略判定作为一般骰子处理。（下个版本会考虑~~改进~~重构）
